name: Update LeetCode Cookies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *"

jobs:
  update_cookies:
    runs-on: ubuntu-latest

    steps:
      - name: Update LeetCode cookies
        uses: vishrutkmr7/UpdateLCCookies@v1.0.0
        with:
          github-token: ${{ secrets.GH_PAT }}
          leetcode-email: ${{ secrets.LEETCODE_USERNAME }}
          leetcode-password: ${{ secrets.LEETCODE_PASSWORD }}

      - name: Trigger sync workflow
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/sync.yml/dispatches \
            -d '{"ref":"main"}'
